<a href="https://colab.research.google.com/github/gupteshmahale04-arch/Numpy/blob/main/Class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [5]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])

#1 addition
print(a+b)

#2 substraction
print(a-b)

#3 Multiplication
print(a*b)

[11 22 33]
[ 9 18 27]
[10 40 90]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [10]:
import numpy as np
a = np.array([10,20,30])
print(a * 5)

[ 50 100 150]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [7]:
A = np.array([10,20,30])

#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [8]:
#Basic statistical operation perfrom
arr = np.array([4,78,21,34,100,56])
#1 sum
print(f"sum is {arr.sum()}")

#2 mean
print(f"Mean(Average) is: {arr.mean()}")

#3 min
print(f"Min is : {arr.min()}")

#4 max
print(f"Min is : {arr.max()}")

#5 standard deviation
print(f"Standard Deviation : {arr.std()}")

#6 Variance
print(f"Variance : {arr.var()}")


sum is 293
Mean(Average) is: 48.833333333333336
Min is : 4
Min is : 100
Standard Deviation : 32.97684372741306
Variance : 1087.4722222222224


You can also do the axis based operations row-Wise and Colum-wise

In [9]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(f"Sum of all: {data.sum()}")

#axis = 0 -> columns
#axis = 1 -> rows
print(f"Sum of columns : {np.sum(data, axis = 0)}")
print(f"Sum of rows : {np.sum(data, axis = 1)}")

Sum of all: 45
Sum of columns : [12 15 18]
Sum of rows : [ 6 15 24]
